name: Metrics
on:
  schedule: [ { cron: "0 0 * * *" } ]
  workflow_dispatch:
  push: { branches: [ "main" ] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: KennethTrecy/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: regular
          output_action: commit
          committer_branch: main
          committer_message: "chore(stat): update metrics"
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_activity: yes
          delay: 10
          base_indepth: yes
          commits_authoring: KennethTrecy, 19201.tobias.kennethtrecy.c@gmail.com, web.kennethtobias@gmail.com, 33564322+KennethTrecy@users.noreply.github.com
          repositories: 200
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          plugin_calendar: yes
          plugin_calendar_limit: 2
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_other: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 184
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_indepth: yes
          plugin_lines: yes
          plugin_lines_sections: base, history
          plugin_lines_history_limit: 2
          plugin_traffic: yes
          config_order: base.header, introduction, base.activity+community, base.repositories, achievements, followup, languages, activity, lines, isocalendar, calendar
