name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: { branches: [ "master" ] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: KennethTrecy/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: large
          output_action: commit
          committer_branch: main
          committer_message: "chore(stat): update metrics"
