name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: { branches: [ "main" ] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: KennethTrecy/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: regular
          output_action: commit
          committer_branch: main
          committer_message: "chore(stat): update metrics"
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_activity: yes
          base_indepth: yes
          repositories_affiliations: owner, collaborator
          plugin_calendar: yes
          plugin_calendar_limit: 2
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_indepth: yes
          plugin_lines: yes
          plugin_lines_sections: base, history
          plugin_lines_repositories_limit: 10
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_traffic: yes
          config_order: base.header, introduction, base.activity+community, base.repositories, achievements, followup, languages, activity, notable, lines, isocalendar, calendar
